export const lobby = require("../../../assets/lobby.jpeg")
export const wine = require("../../../assets/wine.jpeg")
export const hotelBeach1 = require('../../../assets/hotel-beach.jpeg')
export const bar = require("../../../assets/hotel-bar.jpeg")
export const kitch = require('../../../assets/kitchen.jpeg')
export const limpopo = require('../../../assets/limpopo-hotels.jpeg')
export const red = require('../../../assets/red-couches.jpeg')
export const venda = require('../../../assets/venda-hotels.jpeg')
export const sand = require('../../../assets/sandton-hotels.jpeg')
export const purple=require('../../../assets/purple.jpeg')
export const hotel3=require('../../../assets/hotel3.jpeg')
export const hotel4=require('../../../assets/hotel4.jpeg')
export const hotel5=require('../../../assets/hotel5.jpeg')
export const hotel6=require('../../../assets/hotel6.jpeg')
export const hotel2=require('../../../assets/hotel2.jpeg')
export const hotel8=require('../../../assets/hotel8.jpeg')
export const hotel9=require('../../../assets/hotel9.jpeg')
export const hotel10=require('../../../assets/hotel10.jpeg')
export const hotel11=require('../../../assets/hotel11.jpeg')
export const livingroom1=require('../../../assets/livingroom1.jpeg')
export const livingroom2=require('../../../assets/livingroom2.jpeg')
export const livingroom3=require('../../../assets/livingroom3.jpeg')
export const livingroom4=require('../../../assets/livingroom4.jpeg')
export const livingroom5=require('../../../assets/livingroom5.jpeg')
export const livingroom6=require('../../../assets/livingroom6.jpeg')
export const livingroom7=require('../../../assets/livingroom7.jpeg')
export const singles = require('../../../assets/singless.jpeg')
export const redo = require('../../../assets/redo.jpeg')
export const bed5 = require('../../../assets/bed5.jpeg')
export const bed3 = require('../../../assets/bed3.jpeg')
export const bed4 = require('../../../assets/bed4.jpeg')
export const bed6 = require('../../../assets/bed6.jpeg')

export default{
    lobby,wine,hotelBeach1,bar,kitch,limpopo,red,venda,sand,purple,hotel10,hotel11,hotel2,hotel3,hotel4,hotel5,hotel6,hotel8,hotel9 ,livingroom1,livingroom2,livingroom3,livingroom4,livingroom5,livingroom6,livingroom7,singles,redo,bed5,bed3,bed4,bed6
}